//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAP
{
    using System;
    
    public partial class ComprobarPass_Result1
    {
        public int id_cliente { get; set; }
        public string txt_nombre_cliente { get; set; }
        public string txt_apellidos_cliente { get; set; }
        public string int_celular_cliente { get; set; }
        public string txt_correo_cliente { get; set; }
        public byte[] txt_contraseña_cliente { get; set; }
        public string Pass { get; set; }
    }
}
