//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAP
{
    using System;
    
    public partial class GetPedidos_Result1
    {
        public int id_pedido { get; set; }
        public System.DateTime d_fecha_pedido { get; set; }
        public decimal dec_total_pedido { get; set; }
        public string txt_estado_pedido { get; set; }
        public string txt_tipo_prenda { get; set; }
        public string txt_marca_prenda { get; set; }
        public decimal dec_precio_prenda { get; set; }
        public string img_blanco_prenda { get; set; }
        public string img_negro_prenda { get; set; }
        public string txt_color_prenda { get; set; }
        public string txt_talla_prenda { get; set; }
        public int int_cantidad_subpedido { get; set; }
        public int id_cliente { get; set; }
    }
}
