//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.variantes_producto = new HashSet<variantes_producto>();
        }
    
        public int id_prenda { get; set; }
        public string txt_tipo_prenda { get; set; }
        public string txt_concepto_prenda { get; set; }
        public string txt_marca_prenda { get; set; }
        public decimal dec_precio_prenda { get; set; }
        public string img_blanco_prenda { get; set; }
        public string img_negro_prenda { get; set; }
        public string txt_estado_prenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<variantes_producto> variantes_producto { get; set; }
    }
}
